In [3]:
import re
import numpy as np
import pandas as pd

Каждая строка в файле соответствует одному предложению. 
Считайте их, приведите каждую к нижнему регистру с помощью строковой функции lower()

In [4]:
with open('sentences1.txt', 'r') as file_obj:
    words = set([])
    #p = 0
    for line in file_obj:
        line = line.lower()
        line = re.split('[^a-z]',line)
        line = ' '.join(line).split()
        words.update(set(line))
        #print(line)
        #p += 1
       
    words = list(words)
    #print(words)
    words = dict(zip(words,range(len(words))))
    #print(words)
    #print(p)
    #for word in words:
    #    words[str(word)] = [words[str(word)]]
    #    words[str(word)].append(0)
    file_obj.seek(0)
    #count words appearance in 
    i = 0
    matrix = np.zeros((22,254))
    for line in file_obj:
        line = line.lower()
        line = re.split('[^a-z]',line)
        line = ' '.join(line).split()
        for word in line:
            if word in words:
                matrix[i,words[word]] += 1
        i +=1
    print(matrix)
    print(matrix.shape)

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(22, 254)


Создайте матрицу размера n * d, где n — число предложений. Заполните ее: элемент с индексом (i, j) в этой матрице должен быть равен количеству вхождений j-го слова в i-е предложение. У вас должна получиться матрица размера 22 * 254.

In [5]:
dist_matrix = np.zeros((21,1))
print(dist_matrix[0:23])

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [6]:
from scipy.spatial import distance
for i in range(0,21):
    dist_matrix[i] = distance.cosine(matrix[0,:],matrix[i+1,:])
#print(dist_matrix)
#print(dist_matrix.min())
min_1 = np.argmin(dist_matrix)+1
#print(np.argmin(dist_matrix) + 1) 
dist_matrix[np.argmin(dist_matrix),0] = 1
#print(dist_matrix)
min_2 = np.argmin(dist_matrix)+ 1
#dist_matrix[0,0] = 0 
print(min_2)
#print(np.argmax(dist_matrix)+ 1)

4


In [7]:
file = open('assignment.txt', 'w')
file.write(str(min_1) + ' ' + str(min_2) )
file.close()

## Задача 1: сравнение предложений
### 1. Считывание предложений из файла. Приведение к нижнему регистру.
### 2. Произвести токенизацию (разбиение текстов на слова). Удалить пустые слова.

In [8]:
import re
sentences = []
with open('sentences1.txt', 'r') as file_obj:
    words = set([])
    for line in file_obj:
        line = line.lower()
        line = re.split('[^a-z]',line)
        line = ' '.join(line).split()
        sentences.append(line)
for sentence in sentences:
    print(sentence)

['in', 'comparison', 'to', 'dogs', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process']
['as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes']
['a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output']
['cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals']
['in', 'one', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin']
['the', 'domesticated', 'cat', 'and', 'its', 'closest', 'wild', 'ancestor', 'are', 'both', 'diploid', 'organisms', 't

### 3. Составить список всех слов.


In [9]:
words_dict = {}

i = 0 
for sentence in sentences:
    for word in sentence:
        if word not in words_dict:
            words_dict[word] = i
            i += 1
for word in words_dict:
    print (word, " : ", words_dict[word])

in  :  0
comparison  :  1
to  :  2
dogs  :  3
cats  :  4
have  :  5
not  :  6
undergone  :  7
major  :  8
changes  :  9
during  :  10
the  :  11
domestication  :  12
process  :  13
as  :  14
cat  :  15
simply  :  16
catenates  :  17
streams  :  18
of  :  19
bytes  :  20
it  :  21
can  :  22
be  :  23
also  :  24
used  :  25
concatenate  :  26
binary  :  27
files  :  28
where  :  29
will  :  30
just  :  31
sequence  :  32
a  :  33
common  :  34
interactive  :  35
use  :  36
for  :  37
single  :  38
file  :  39
is  :  40
output  :  41
content  :  42
standard  :  43
hear  :  44
sounds  :  45
too  :  46
faint  :  47
or  :  48
high  :  49
frequency  :  50
human  :  51
ears  :  52
such  :  53
those  :  54
made  :  55
by  :  56
mice  :  57
and  :  58
other  :  59
small  :  60
animals  :  61
one  :  62
people  :  63
deliberately  :  64
tamed  :  65
artificial  :  66
selection  :  67
they  :  68
were  :  69
useful  :  70
predators  :  71
vermin  :  72
domesticated  :  73
its  :  74
closest  :  

In [10]:
print (len(words_dict))

254


In [11]:
framewords = pd.DataFrame(words_dict, range(len(sentences)))
rows, colums = framewords.shape
print(rows, colums)


22 254


In [12]:
for i in range(rows):
    for j in range(colums):
        framewords.iloc[i,j] = 0
framewords

in  comparison  to  dogs  cats  have  not  undergone  major  changes  ...  \
0    0           0   0     0     0     0    0          0      0        0  ...   
1    0           0   0     0     0     0    0          0      0        0  ...   
2    0           0   0     0     0     0    0          0      0        0  ...   
3    0           0   0     0     0     0    0          0      0        0  ...   
4    0           0   0     0     0     0    0          0      0        0  ...   
5    0           0   0     0     0     0    0          0      0        0  ...   
6    0           0   0     0     0     0    0          0      0        0  ...   
7    0           0   0     0     0     0    0          0      0        0  ...   
8    0           0   0     0     0     0    0          0      0        0  ...   
9    0           0   0     0     0     0    0          0      0        0  ...   
10   0           0   0     0     0     0    0          0      0        0  ...   
11   0           0   0     0     0     0    0          0      0        0  ...   
12   0           0   0     0     0     0    0          0      0        0  ...   
13   0           0   0     0     0     0    0          0      0        0  ...   
14   0           0   0     0     0     0    0          0      0        0  ...   
15   0           0   0     0     0     0    0          0      0        0  ...   
16   0           0   0     0     0     0    0          0      0        0  ...   
17   0           0   0     0     0     0    0          0      0        0  ...   
18   0           0   0     0     0     0    0          0      0        0  ...   
19   0           0   0     0     0     0    0          0      0        0  ...   
20   0           0   0     0     0     0    0          0      0        0  ...   
21   0           0   0     0     0     0    0          0      0        0  ...   

    disk  run  off  external  drive  fifth  update  features  more  count  
0      0    0    0         0      0      0       0         0     0      0  
1      0    0    0         0      0      0       0         0     0      0  
2      0    0    0         0      0      0       0         0     0      0  
3      0    0    0         0      0      0       0         0     0      0  
4      0    0    0         0      0      0       0         0     0      0  
5      0    0    0         0      0      0       0         0     0      0  
6      0    0    0         0      0      0       0         0     0      0  
7      0    0    0         0      0      0       0         0     0      0  
8      0    0    0         0      0      0       0         0     0      0  
9      0    0    0         0      0      0       0         0     0      0  
10     0    0    0         0      0      0       0         0     0      0  
11     0    0    0         0      0      0       0         0     0      0  
12     0    0    0         0      0      0       0         0     0      0  
13     0    0    0         0      0      0       0         0     0      0  
14     0    0    0         0      0      0       0         0     0      0  
15     0    0    0         0      0      0       0         0     0      0  
16     0    0    0         0      0      0       0         0     0      0  
17     0    0    0         0      0      0       0         0     0      0  
18     0    0    0         0      0      0       0         0     0      0  
19     0    0    0         0      0      0       0         0     0      0  
20     0    0    0         0      0      0       0         0     0      0  
21     0    0    0         0      0      0       0         0     0      0  

[22 rows x 254 columns]

In [13]:
for i in range(len(sentences)):
    for word in sentences[i]:
        framewords.iloc[i][word] +=1
framewords

in  comparison  to  dogs  cats  have  not  undergone  major  changes  ...  \
0    1           1   1     1     1     1    1          1      1        1  ...   
1    0           0   1     0     0     0    0          0      0        0  ...   
2    0           0   2     0     0     0    0          0      0        0  ...   
3    1           0   0     0     1     0    0          0      0        0  ...   
4    2           0   0     0     1     0    0          0      0        0  ...   
5    0           0   0     0     0     0    0          0      0        0  ...   
6    1           0   1     0     1     0    0          0      0        0  ...   
7    0           0   0     0     0     0    0          0      0        0  ...   
8    0           0   1     0     0     0    0          0      0        0  ...   
9    1           0   1     0     0     0    0          0      0        0  ...   
10   1           0   0     0     0     0    0          0      0        0  ...   
11   0           0   1     0     0     0    0          0      0        0  ...   
12   1           0   0     0     0     0    0          0      0        0  ...   
13   1           0   0     0     0     0    0          0      0        0  ...   
14   0           0   1     0     0     0    0          0      0        1  ...   
15   0           0   0     0     0     1    0          0      0        0  ...   
16   1           0   2     0     0     0    0          0      0        0  ...   
17   0           0   1     0     0     0    0          0      0        0  ...   
18   0           0   0     0     0     0    0          0      0        0  ...   
19   0           0   0     0     0     0    0          0      0        0  ...   
20   1           0   1     0     0     0    0          0      0        0  ...   
21   0           0   1     0     0     0    0          0      1        0  ...   

    disk  run  off  external  drive  fifth  update  features  more  count  
0      0    0    0         0      0      0       0         0     0      0  
1      0    0    0         0      0      0       0         0     0      0  
2      0    0    0         0      0      0       0         0     0      0  
3      0    0    0         0      0      0       0         0     0      0  
4      0    0    0         0      0      0       0         0     0      0  
5      0    0    0         0      0      0       0         0     0      0  
6      0    0    0         0      0      0       0         0     0      0  
7      0    0    0         0      0      0       0         0     0      0  
8      0    0    0         0      0      0       0         0     0      0  
9      0    0    0         0      0      0       0         0     0      0  
10     0    0    0         0      0      0       0         0     0      0  
11     0    0    0         0      0      0       0         0     0      0  
12     0    0    0         0      0      0       0         0     0      0  
13     0    0    0         0      0      0       0         0     0      0  
14     0    0    0         0      0      0       0         0     0      0  
15     0    0    0         0      0      0       0         0     0      0  
16     0    0    0         0      0      0       0         0     0      0  
17     0    0    0         0      0      0       0         0     0      0  
18     0    0    0         0      0      0       0         0     0      0  
19     0    0    0         0      0      0       0         0     0      0  
20     1    1    1         1      1      0       0         0     0      0  
21     0    0    0         0      0      1       1         1     1      1  

[22 rows x 254 columns]

### 6. Найти косинусное расстояние от предложения в самой первой строке до всех остальных.

In [14]:
from scipy.spatial.distance import cosine

In [15]:
distance_1_sentence =[]

for i in range(rows):
    distance_1_sentence.append(cosine(framewords.iloc[0],framewords.iloc[i] ))

print( distance_1_sentence)

[0.0, 0.9527544408738466, 0.8644738145642124, 0.8951715163278082, 0.7770887149698589, 0.9402385695332803, 0.7327387580875756, 0.9258750683338899, 0.8842724875284311, 0.9055088817476932, 0.8328165362273942, 0.8804771390665607, 0.8396432548525454, 0.8703592552895671, 0.8740118423302576, 0.9442721787424647, 0.8406361854220809, 0.956644501523794, 0.9442721787424647, 0.8885443574849294, 0.8427572744917122, 0.8250364469440588]


In [16]:
distance_1_sentence_copy = list(distance_1_sentence)
twoClosestValues = [[-1, 0], [-1, 0]]

distance_1_sentence.remove(min(distance_1_sentence_copy))

for i in range(2):
    twoClosestValues[i][1] = min(distance_1_sentence_copy)

    for j in range(len(distance_1_sentence)):
        if twoClosestValues[i][1] == distance_1_sentence[j]:
            
            twoClosestValues[i][0] = j
    distance_1_sentence_copy.remove(min(distance_1_sentence_copy))
    
twoClosestValues = sorted(twoClosestValues)
twoClosestValues

[[-1, 0.0], [5, 0.7327387580875756]]